# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountriesFacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountriesFacts
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
end
